import type { exercises } from "../schema/exercises";

/**
 * The stock exercise directory.
 *
 * Every attribute here is read by something downstream, so none of it is
 * decoration:
 *
 * - `loadsTendonSites` and `tendonLoadRating` drive the pre-filter. A site in
 *   protocol phase 1 or 2 removes every exercise listing it, which is how tendon
 *   safety becomes impossible to violate rather than merely checked. Unilateral
 *   drills list both sides, because in practice they are prescribed for both;
 *   training only the healthy side is a deliberate edit, not a default.
 * - `highImpact` is the unit the weekly contact ceiling is counted in.
 * - `couplingClass` and `typicalContactSeconds` gate shock-method labelling. The
 *   ebook's line is 0.15 s, so anything slower is not shock work whatever it is
 *   called, and the normalizer enforces that.
 * - `technicalComplexity` and `forceVelocity` drive session ordering: the most
 *   coordination-demanding and most dynamic work goes first, while rested.
 *
 * `couplingClass` for the non-plyometric lifts is left at the schema default.
 * Squat jumps are `non_classical` rather than a short or long SSC because a
 * static start has no countermovement to couple.
 */
export type SeedExercise = Omit<
  typeof exercises.$inferInsert,
  "id" | "createdAt" | "updatedAt" | "isStock" | "progressionOfId" | "regressionOfId"
> & {
  /** Slug of the exercise this one progresses from, resolved after insert. */
  progressionOf?: string;
};

const PATELLAR = ["patellar_left", "patellar_right"] as const;
const ACHILLES = ["achilles_left", "achilles_right"] as const;
const BOTH_KNEE_AND_ANKLE = [...PATELLAR, ...ACHILLES];

export const STOCK_EXERCISES: SeedExercise[] = [
  // ---------------------------------------------------------------------------
  // Jump testing and technique. These are the sport exercise, so they lead
  // sessions and carry the highest technical complexity.
  // ---------------------------------------------------------------------------
  {
    slug: "standing-vertical-jump",
    name: "Standing vertical jump",
    primaryMuscleGroup: "full_body",
    secondaryMuscleGroups: ["knee_extensors", "posterior_chain", "lower_leg"],
    movementPattern: "jump_bilateral",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "long_ssc",
    typicalContactSeconds: "0.400",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: [
      "Arms up and back, then drive them as high as possible",
      "Extend hip, knee and ankle through the whole jump",
    ],
    notes:
      "The reference test. Depth jump box height is chosen against this number, so it is measured on the same day as any depth jump calibration.",
  },
  {
    slug: "countermovement-jump",
    name: "Countermovement jump",
    primaryMuscleGroup: "full_body",
    secondaryMuscleGroups: ["knee_extensors", "posterior_chain"],
    movementPattern: "jump_bilateral",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "long_ssc",
    typicalContactSeconds: "0.450",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: ["Dip and reverse in one motion", "No pause at the bottom"],
  },
  {
    slug: "squat-jump",
    name: "Squat jump",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain", "lower_leg"],
    movementPattern: "jump_bilateral",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    // Static start: nothing to couple, so this is not an SSC drill at all.
    couplingClass: "non_classical",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 2,
    technicalComplexity: 2,
    cues: ["Hold the bottom for a beat, then go", "No dip before takeoff"],
    notes:
      "Isolates concentric force production by removing the stretch shortening cycle, which makes it the useful contrast against the countermovement jump.",
  },
  {
    slug: "two-foot-approach-jump",
    name: "Two foot approach jump",
    primaryMuscleGroup: "full_body",
    secondaryMuscleGroups: ["posterior_chain", "knee_extensors", "lower_leg"],
    movementPattern: "jump_bilateral",
    forceVelocity: "reactive",
    laterality: "bilateral",
    plane: "multi",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.200",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 4,
    technicalComplexity: 5,
    cues: [
      "Get low 2 to 3 steps out and hold that position",
      "Accelerate through the approach, never slow mid-run",
      "Penultimate foot lands slightly in front of the hips",
      "Kick the plant leg out straight, foot turned slightly outward",
      "Long split between penultimate toe-off and plant touchdown",
    ],
    notes:
      "The penultimate step largely determines the jump: lowest centre of mass, highest horizontal velocity. A slight curved approach lowers you more than a straight one.",
  },
  {
    slug: "one-foot-approach-jump",
    name: "One foot approach jump",
    primaryMuscleGroup: "full_body",
    secondaryMuscleGroups: ["posterior_chain", "knee_extensors", "lower_leg"],
    movementPattern: "jump_unilateral",
    forceVelocity: "reactive",
    laterality: "unilateral",
    plane: "multi",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.140",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 5,
    technicalComplexity: 5,
    cues: [
      "Rhythm accelerates from the first step through takeoff",
      "Lower on a slight inward curve, then hold it until the takeoff foot strikes",
      "Penultimate step: maintain the low position, do not keep sinking",
      "Arm swing matches the leg action in amplitude and speed",
      "Do not think about how much to bend the knee",
    ],
    notes:
      "Loads a leg at up to 14 times bodyweight, the single highest tendon load in the directory. Stride frequency may be the greatest determinant of success. An experienced jumper's speed-versus-power strategy is already set and should not be forced to switch.",
  },
  {
    slug: "broad-jump",
    name: "Broad jump",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["knee_extensors", "lower_leg"],
    movementPattern: "jump_bilateral",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "long_ssc",
    typicalContactSeconds: "0.400",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: ["Drive out at roughly 45 degrees", "Land soft and absorb"],
    notes: "Horizontal power test, and a useful cross-check on the vertical.",
  },

  // ---------------------------------------------------------------------------
  // Plyometrics, ordered roughly by intensity. Conservative defaults on purpose:
  // plyos are the hardest part to get right and can make some athletes jump
  // lower.
  // ---------------------------------------------------------------------------
  {
    slug: "pogo-hop",
    name: "Pogo hop",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "hop",
    forceVelocity: "reactive",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.120",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["Stiff ankles, minimal knee bend", "Off the ground as fast as possible"],
    notes: "The entry point for short SSC work and the lowest-risk stiffness drill.",
  },
  {
    slug: "ankle-hop-single-leg",
    name: "Single leg ankle hop",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "hop",
    forceVelocity: "reactive",
    laterality: "unilateral",
    plane: "sagittal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.130",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: ["Same spot every rep", "Ankle does the work"],
    progressionOf: "pogo-hop",
  },
  {
    slug: "tuck-jump",
    name: "Tuck jump",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["core", "lower_leg"],
    movementPattern: "jump_bilateral",
    forceVelocity: "reactive",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.200",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: ["Knees to chest", "Land and go again immediately"],
    notes: "Multi response drill: emphasises elasticity and coordination.",
  },
  {
    slug: "box-jump",
    name: "Box jump",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain"],
    movementPattern: "jump_bilateral",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "long_ssc",
    typicalContactSeconds: "0.400",
    highImpact: true,
    equipment: ["box"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 2,
    cues: ["Step down, never jump down", "Full extension at takeoff"],
    notes:
      "Low landing load because the box removes the descent. Trains takeoff, not absorption, so it is not a substitute for depth work.",
  },
  {
    slug: "hurdle-hop",
    name: "Hurdle hop",
    primaryMuscleGroup: "lower_leg",
    secondaryMuscleGroups: ["knee_extensors"],
    movementPattern: "hop",
    forceVelocity: "reactive",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.180",
    highImpact: true,
    equipment: ["hurdle"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 3,
    cues: ["Minimal ground contact between hurdles", "Stay tall, do not pike"],
    progressionOf: "pogo-hop",
  },
  {
    slug: "alternate-leg-bound",
    name: "Alternate leg bound",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["knee_extensors", "lower_leg"],
    movementPattern: "bound",
    forceVelocity: "reactive",
    laterality: "alternating",
    plane: "sagittal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.170",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 4,
    technicalComplexity: 3,
    cues: ["Cover distance, not height", "Aggressive hip extension off each leg"],
    notes: "Closest plyometric to the one-foot takeoff pattern.",
  },
  {
    slug: "single-leg-hop-distance",
    name: "Single leg hop for distance",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["knee_extensors", "lower_leg"],
    movementPattern: "hop",
    forceVelocity: "reactive",
    laterality: "unilateral",
    plane: "sagittal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.160",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 4,
    technicalComplexity: 3,
    cues: ["Same leg every rep", "Land through the whole foot"],
    progressionOf: "alternate-leg-bound",
  },
  {
    slug: "lateral-bound",
    name: "Lateral bound",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["knee_extensors"],
    movementPattern: "bound",
    forceVelocity: "reactive",
    laterality: "alternating",
    plane: "frontal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.190",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 3,
    cues: ["Push through the outside leg", "Stick the landing before rebounding"],
    notes:
      "Frontal plane work, which the sagittal jump drills never load. Plane of motion is one of the ebook's spatial overload variables.",
  },
  {
    slug: "depth-landing",
    name: "Depth landing",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain", "lower_leg"],
    movementPattern: "depth_drop",
    forceVelocity: "reactive",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "non_classical",
    highImpact: true,
    equipment: ["box"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: ["Absorb and hold, do not rebound", "Quiet landing"],
    notes:
      "Absorption only. This is phase 3 of the tendon protocol, the point at which enough capacity to play sports develops.",
  },
  {
    slug: "depth-jump",
    name: "Depth jump",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain", "lower_leg"],
    movementPattern: "depth_drop",
    forceVelocity: "shock",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "short_ssc",
    typicalContactSeconds: "0.140",
    highImpact: true,
    equipment: ["box"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 5,
    technicalComplexity: 4,
    cues: [
      "Step off, do not jump off",
      "Ground contact as short as possible",
      "Beat the floor",
    ],
    notes:
      "The shock method, and only while ground contact stays under 0.15 s. Box height is calibrated by raising it until measured vertical drops below the standing jump, then working at the height where the two match. Highest tendon load of any drill here apart from one-foot jumping.",
    progressionOf: "depth-landing",
  },
  {
    slug: "single-leg-depth-jump",
    name: "Single leg depth jump",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain", "lower_leg"],
    movementPattern: "depth_drop",
    forceVelocity: "shock",
    laterality: "unilateral",
    plane: "sagittal",
    couplingClass: "short_ssc",
    // Deliberately not 0.150: the shock-method boundary is exactly there, and a
    // drill sitting on it makes the normalizer's verdict depend on rounding.
    typicalContactSeconds: "0.145",
    highImpact: true,
    equipment: ["box"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 5,
    technicalComplexity: 5,
    cues: ["Low box only", "Abort the set the moment contact time lengthens"],
    notes:
      "Reserved for late realization blocks with healthy tendons. Off by default.",
    available: false,
    progressionOf: "depth-jump",
  },
  {
    slug: "medicine-ball-overhead-throw",
    name: "Medicine ball overhead throw",
    primaryMuscleGroup: "full_body",
    secondaryMuscleGroups: ["core", "posterior_chain", "shoulders"],
    movementPattern: "throw",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["medicine_ball"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Full triple extension into the release", "Throw for distance"],
    notes:
      "Full-body power with no landing impact, which makes it the useful option when tendon load has to come down but intent should not.",
  },
  {
    slug: "medicine-ball-rotational-throw",
    name: "Medicine ball rotational throw",
    primaryMuscleGroup: "core",
    secondaryMuscleGroups: ["posterior_chain", "shoulders"],
    movementPattern: "throw",
    forceVelocity: "speed_strength",
    laterality: "unilateral",
    plane: "transverse",
    equipment: ["medicine_ball"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Rotate from the hip, not the arms"],
  },

  // ---------------------------------------------------------------------------
  // Sprinting. High tendon load, and the reintroduction step the load-management
  // protocol treats as a milestone rather than a warm-up.
  // ---------------------------------------------------------------------------
  {
    slug: "acceleration-sprint",
    name: "Acceleration sprint",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["knee_extensors", "lower_leg"],
    movementPattern: "sprint",
    forceVelocity: "speed_strength",
    laterality: "alternating",
    plane: "sagittal",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 3,
    cues: ["Push the ground back", "Let the torso rise gradually"],
    notes: "Loads a leg at up to 6 times bodyweight.",
  },
  {
    slug: "flying-sprint",
    name: "Flying sprint",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["lower_leg"],
    movementPattern: "sprint",
    forceVelocity: "reactive",
    laterality: "alternating",
    plane: "sagittal",
    highImpact: true,
    equipment: ["none"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 4,
    technicalComplexity: 4,
    cues: ["Build in, then hold top speed relaxed"],
    progressionOf: "acceleration-sprint",
  },
  {
    slug: "sled-push",
    name: "Sled push",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain", "lower_leg"],
    movementPattern: "sprint",
    forceVelocity: "max_strength",
    laterality: "alternating",
    plane: "sagittal",
    equipment: ["sled"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["Long powerful steps", "Stay behind the handles"],
    notes: "Sprint-pattern force with no flight phase, so no impact.",
  },

  // ---------------------------------------------------------------------------
  // Lower body strength. Max strength helps power; the reverse is not true, so
  // these anchor accumulation blocks.
  // ---------------------------------------------------------------------------
  {
    slug: "back-squat",
    name: "Back squat",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain", "core"],
    movementPattern: "squat",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell", "rack"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 3,
    technicalComplexity: 3,
    cues: ["Brace before you descend", "Knees track over the toes"],
    notes:
      "Deeper positions demand more torque, and compound movements transfer better because jumping is intermuscularly complex.",
  },
  {
    slug: "front-squat",
    name: "Front squat",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["core"],
    movementPattern: "squat",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell", "rack"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 4,
    technicalComplexity: 4,
    cues: ["Elbows up", "Stay upright through the whole rep"],
    notes: "More knee-extensor and patellar load than the back squat at equal bar weight.",
  },
  {
    slug: "box-squat",
    name: "Box squat",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain"],
    movementPattern: "squat",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell", "rack", "box"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 2,
    cues: ["Sit back to the box", "Pause, then drive"],
    notes: "Breaks the stretch shortening cycle, so it trains concentric force from a dead stop.",
  },
  {
    slug: "trap-bar-deadlift",
    name: "Trap bar deadlift",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["knee_extensors", "core"],
    movementPattern: "hinge",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["trap_bar"],
    tendonLoadRating: 2,
    technicalComplexity: 2,
    cues: ["Push the floor away", "Hips and shoulders rise together"],
    notes: "The highest-load option that stays gentle on the patellar tendon.",
  },
  {
    slug: "romanian-deadlift",
    name: "Romanian deadlift",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["core"],
    movementPattern: "hinge",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Hinge, do not squat", "Bar stays against the legs"],
  },
  {
    slug: "hip-thrust",
    name: "Barbell hip thrust",
    primaryMuscleGroup: "posterior_chain",
    movementPattern: "hinge",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell", "bench"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Ribs down", "Finish with the glutes, not the lower back"],
  },
  {
    slug: "nordic-hamstring-curl",
    name: "Nordic hamstring curl",
    primaryMuscleGroup: "posterior_chain",
    movementPattern: "hinge",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["none"],
    tendonLoadRating: 2,
    technicalComplexity: 3,
    cues: ["Lower as slowly as you can control", "Hips stay extended"],
  },
  {
    slug: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain"],
    movementPattern: "lunge",
    forceVelocity: "max_strength",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["dumbbell", "bench"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: ["Front shin roughly vertical", "Control the descent"],
  },
  {
    slug: "reverse-lunge",
    name: "Reverse lunge",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain"],
    movementPattern: "lunge",
    forceVelocity: "max_strength",
    laterality: "alternating",
    plane: "sagittal",
    equipment: ["dumbbell"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["Step back and down", "Torso stays tall"],
  },
  {
    slug: "step-up",
    name: "Step up",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain"],
    movementPattern: "lunge",
    forceVelocity: "max_strength",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["dumbbell", "box"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["Drive through the top leg", "No push off the trailing foot"],
  },
  {
    slug: "single-leg-rdl",
    name: "Single leg Romanian deadlift",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["core"],
    movementPattern: "hinge",
    forceVelocity: "max_strength",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["dumbbell"],
    tendonLoadRating: 1,
    technicalComplexity: 3,
    cues: ["Hips square", "Reach the free leg back as a counterweight"],
  },
  {
    slug: "jump-squat-loaded",
    name: "Loaded jump squat",
    primaryMuscleGroup: "knee_extensors",
    secondaryMuscleGroups: ["posterior_chain", "lower_leg"],
    movementPattern: "jump_bilateral",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "long_ssc",
    typicalContactSeconds: "0.450",
    highImpact: true,
    equipment: ["barbell", "dumbbell"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 4,
    technicalComplexity: 3,
    cues: ["Light load, maximum intent", "Stop the set when speed drops"],
    notes: "Resistive overload of the jump pattern, one of the ebook's overload variables.",
  },
  {
    slug: "trap-bar-jump",
    name: "Trap bar jump",
    primaryMuscleGroup: "posterior_chain",
    secondaryMuscleGroups: ["knee_extensors", "lower_leg"],
    movementPattern: "jump_bilateral",
    forceVelocity: "speed_strength",
    laterality: "bilateral",
    plane: "sagittal",
    couplingClass: "long_ssc",
    highImpact: true,
    equipment: ["trap_bar"],
    loadsTendonSites: BOTH_KNEE_AND_ANKLE,
    tendonLoadRating: 3,
    technicalComplexity: 2,
    cues: ["Jump, then let the bar settle", "Reset every rep"],
    notes: "Loaded jumping with the spine unloaded compared with a barbell on the back.",
  },
  {
    slug: "standing-calf-raise",
    name: "Standing calf raise",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "calf_raise",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["machine", "dumbbell"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["Full range, pause at the top"],
  },
  {
    slug: "seated-calf-raise",
    name: "Seated calf raise",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "calf_raise",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["machine"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["Knee bent, so the soleus takes the load"],
  },
  {
    slug: "single-leg-calf-raise",
    name: "Single leg calf raise",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "calf_raise",
    forceVelocity: "max_strength",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["none"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["Off a step for full range", "Slow down, slow up"],
  },
  {
    slug: "tibialis-raise",
    name: "Tibialis raise",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "calf_raise",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["none", "band"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Pull the toes up hard"],
    notes: "Balances the anterior shin against high posterior loading from jumping.",
  },

  // ---------------------------------------------------------------------------
  // Tendon load-management protocol. Isometrics are analgesic for up to 90
  // minutes and restore activation patterns that pain inhibits, which is why
  // they are phase 1 rather than rest.
  // ---------------------------------------------------------------------------
  {
    slug: "spanish-squat-isometric",
    name: "Spanish squat isometric",
    primaryMuscleGroup: "knee_extensors",
    movementPattern: "isometric_hold",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["band", "rack"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Hold at roughly 70 percent effort", "Breathe through the hold"],
    notes:
      "Patellar protocol phase 1: 5 x 45 s at about 70 percent maximum voluntary contraction, three times a day, roughly every 6 hours. Loads the tendon while avoiding speed and length change.",
  },
  {
    slug: "single-leg-extension-isometric",
    name: "Single leg extension isometric",
    primaryMuscleGroup: "knee_extensors",
    movementPattern: "isometric_hold",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["machine"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Mid-range hold, no lockout"],
    notes: "Patellar protocol phase 1, per side, when the affected side needs isolating.",
  },
  {
    slug: "isometric-calf-hold",
    name: "Isometric calf hold",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "isometric_hold",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["none"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Hold high on the toes", "Do not let the heel drift down"],
    notes: "Achilles protocol phase 1.",
  },
  {
    slug: "slow-heavy-leg-extension",
    name: "Slow heavy leg extension",
    primaryMuscleGroup: "knee_extensors",
    movementPattern: "isometric_hold",
    forceVelocity: "max_strength",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["machine"],
    loadsTendonSites: PATELLAR.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["4 seconds down, 4 seconds up"],
    notes:
      "Patellar protocol phase 2: 3 to 4 x 6 to 8, every other day, adding 5 to 20 lb per session. Raises tendon stiffness and capacity.",
    progressionOf: "single-leg-extension-isometric",
  },
  {
    slug: "slow-heavy-calf-raise",
    name: "Slow heavy calf raise",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "calf_raise",
    forceVelocity: "max_strength",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["machine", "dumbbell"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 2,
    technicalComplexity: 1,
    cues: ["4 seconds down, 4 seconds up"],
    notes: "Achilles protocol phase 2.",
    progressionOf: "isometric-calf-hold",
  },

  // ---------------------------------------------------------------------------
  // Upper body. Not incidental: relative strength is what predicts jumping, so
  // upper body work is programmed for its own sake and audited for the
  // bodyweight it adds.
  // ---------------------------------------------------------------------------
  {
    slug: "bench-press",
    name: "Bench press",
    primaryMuscleGroup: "upper_push",
    secondaryMuscleGroups: ["shoulders"],
    movementPattern: "push_horizontal",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell", "bench", "rack"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Shoulder blades back and down", "Bar to the lower chest"],
  },
  {
    slug: "incline-dumbbell-press",
    name: "Incline dumbbell press",
    primaryMuscleGroup: "upper_push",
    secondaryMuscleGroups: ["shoulders"],
    movementPattern: "push_horizontal",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["dumbbell", "bench"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Elbows at about 45 degrees"],
  },
  {
    slug: "overhead-press",
    name: "Overhead press",
    primaryMuscleGroup: "shoulders",
    secondaryMuscleGroups: ["upper_push", "core"],
    movementPattern: "push_vertical",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell", "rack"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Brace the ribs down", "Head through at the top"],
  },
  {
    slug: "dip",
    name: "Dip",
    primaryMuscleGroup: "upper_push",
    secondaryMuscleGroups: ["shoulders"],
    movementPattern: "push_vertical",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["dip_station", "weight_vest"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Slight forward lean", "Stop where the shoulder stays comfortable"],
  },
  {
    slug: "push-up",
    name: "Push up",
    primaryMuscleGroup: "upper_push",
    secondaryMuscleGroups: ["core", "shoulders"],
    movementPattern: "push_horizontal",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["none", "weight_vest"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["One straight line from head to heels"],
  },
  {
    slug: "pull-up",
    name: "Pull up",
    primaryMuscleGroup: "upper_pull",
    secondaryMuscleGroups: ["shoulders", "core"],
    movementPattern: "pull_vertical",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["pullup_bar", "weight_vest"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Chest to the bar", "Control the descent"],
  },
  {
    slug: "chin-up",
    name: "Chin up",
    primaryMuscleGroup: "upper_pull",
    movementPattern: "pull_vertical",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["pullup_bar", "weight_vest"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Supinated grip, elbows down and back"],
  },
  {
    slug: "lat-pulldown",
    name: "Lat pulldown",
    primaryMuscleGroup: "upper_pull",
    movementPattern: "pull_vertical",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["cable", "machine"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Lead with the elbows"],
  },
  {
    slug: "barbell-row",
    name: "Barbell row",
    primaryMuscleGroup: "upper_pull",
    secondaryMuscleGroups: ["posterior_chain", "core"],
    movementPattern: "pull_horizontal",
    forceVelocity: "max_strength",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell"],
    tendonLoadRating: 1,
    technicalComplexity: 3,
    cues: ["Flat back", "Pull to the lower ribs"],
  },
  {
    slug: "single-arm-dumbbell-row",
    name: "Single arm dumbbell row",
    primaryMuscleGroup: "upper_pull",
    secondaryMuscleGroups: ["core"],
    movementPattern: "pull_horizontal",
    forceVelocity: "max_strength",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["dumbbell", "bench"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["No torso rotation"],
  },
  {
    slug: "inverted-row",
    name: "Inverted row",
    primaryMuscleGroup: "upper_pull",
    secondaryMuscleGroups: ["core"],
    movementPattern: "pull_horizontal",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["barbell", "rack", "gym_rings"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Body stays rigid", "Chest to the bar"],
  },
  {
    slug: "lateral-raise",
    name: "Lateral raise",
    primaryMuscleGroup: "shoulders",
    movementPattern: "push_vertical",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "frontal",
    equipment: ["dumbbell", "cable"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Lead with the elbow, not the hand"],
  },
  {
    slug: "face-pull",
    name: "Face pull",
    primaryMuscleGroup: "shoulders",
    secondaryMuscleGroups: ["upper_pull"],
    movementPattern: "pull_horizontal",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "transverse",
    equipment: ["cable", "band"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Pull to the forehead, thumbs back"],
    notes: "Shoulder balance against pressing volume.",
  },

  // ---------------------------------------------------------------------------
  // Core and carries. Bracing transmits force from the ground to the trunk, so
  // this is not accessory work for a jumper.
  // ---------------------------------------------------------------------------
  {
    slug: "hanging-leg-raise",
    name: "Hanging leg raise",
    primaryMuscleGroup: "core",
    movementPattern: "brace",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["pullup_bar"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["No swing", "Curl the pelvis at the top"],
  },
  {
    slug: "ab-wheel-rollout",
    name: "Ab wheel rollout",
    primaryMuscleGroup: "core",
    movementPattern: "brace",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["ab_wheel"],
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Ribs down the whole way out"],
  },
  {
    slug: "plank",
    name: "Plank",
    primaryMuscleGroup: "core",
    movementPattern: "isometric_hold",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["none"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Squeeze glutes, tuck the ribs"],
  },
  {
    slug: "side-plank",
    name: "Side plank",
    primaryMuscleGroup: "core",
    movementPattern: "isometric_hold",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "frontal",
    equipment: ["none"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Hips stacked and lifted"],
  },
  {
    slug: "pallof-press",
    name: "Pallof press",
    primaryMuscleGroup: "core",
    movementPattern: "brace",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "transverse",
    equipment: ["cable", "band"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Resist the rotation, do not create it"],
  },
  {
    slug: "farmers-carry",
    name: "Farmer's carry",
    primaryMuscleGroup: "core",
    secondaryMuscleGroups: ["upper_pull", "shoulders"],
    movementPattern: "carry",
    forceVelocity: "non_specific",
    laterality: "bilateral",
    plane: "sagittal",
    equipment: ["dumbbell", "kettlebell"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Tall and quiet, no lean"],
  },
  {
    slug: "suitcase-carry",
    name: "Suitcase carry",
    primaryMuscleGroup: "core",
    movementPattern: "carry",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "frontal",
    equipment: ["dumbbell", "kettlebell"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Do not let the loaded side pull you over"],
  },

  // ---------------------------------------------------------------------------
  // Mobility. Note that stretching the tendon is explicitly not part of tendon
  // management, so nothing here is prescribed as pain treatment.
  // ---------------------------------------------------------------------------
  {
    slug: "ankle-dorsiflexion-mobilization",
    name: "Ankle dorsiflexion mobilisation",
    primaryMuscleGroup: "lower_leg",
    movementPattern: "mobility",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["none", "band"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Knee over the toes, heel stays down"],
    notes: "Dorsiflexion range limits how low the penultimate step can get.",
  },
  {
    slug: "hip-flexor-stretch",
    name: "Hip flexor stretch",
    primaryMuscleGroup: "posterior_chain",
    movementPattern: "mobility",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "sagittal",
    equipment: ["none"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Tuck the pelvis before you lean"],
  },
  {
    slug: "adductor-rockback",
    name: "Adductor rockback",
    primaryMuscleGroup: "posterior_chain",
    movementPattern: "mobility",
    forceVelocity: "non_specific",
    laterality: "unilateral",
    plane: "frontal",
    equipment: ["none"],
    tendonLoadRating: 1,
    technicalComplexity: 1,
    cues: ["Rock back slowly, stay square"],
  },
  {
    slug: "a-skip",
    name: "A skip",
    primaryMuscleGroup: "lower_leg",
    secondaryMuscleGroups: ["posterior_chain"],
    movementPattern: "sprint",
    forceVelocity: "non_specific",
    laterality: "alternating",
    plane: "sagittal",
    equipment: ["none"],
    loadsTendonSites: ACHILLES.slice(),
    tendonLoadRating: 1,
    technicalComplexity: 2,
    cues: ["Tall posture, quick ground contact", "Knee up, foot down"],
    notes: "Warm-up and rhythm drill; rhythm is the skill the one-foot jump depends on most.",
  },
];
